-- Carrom Board Tournament Database Schema
-- Paste this script directly into the Supabase SQL Editor

-- 1. Create 'players' table
CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INT NOT NULL,
    name TEXT NOT NULL,
    skill_rating INT NOT NULL,
    team_id INT,
    partner_pref TEXT,
    location TEXT NOT NULL
);

-- 2. Create 'teams' table
CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL,
    team_name TEXT NOT NULL,
    avg_skill REAL,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    is_eliminated BOOLEAN DEFAULT FALSE,
    location TEXT NOT NULL
);

-- 3. Create 'matches' table
CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INT NOT NULL,
    round INT NOT NULL,
    team_a_id INT,
    team_b_id INT,
    winner_id INT,
    loser_id INT,
    bracket TEXT,
    status TEXT,
    scheduled_date TEXT,
    scheduled_time TEXT,
    date_played TEXT,
    team_a_score INT,
    team_b_score INT,
    location TEXT NOT NULL
);

-- 4. Create 'match_stats' table
CREATE TABLE IF NOT EXISTS match_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_id INT NOT NULL,
    match_id INT NOT NULL,
    player_id INT NOT NULL,
    team_id INT,
    queen_snatcher BOOLEAN DEFAULT FALSE,
    precision_player BOOLEAN DEFAULT FALSE,
    best_striker BOOLEAN DEFAULT FALSE,
    comeback_king BOOLEAN DEFAULT FALSE,
    location TEXT NOT NULL
);

-- 5. Create 'leaderboard' table
CREATE TABLE IF NOT EXISTS leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rank INT,
    team_id INT,
    team_name TEXT,
    wins INT,
    losses INT,
    status TEXT,
    total_points INT,
    total_awards INT,
    location TEXT NOT NULL
);

-- 6. Create 'player_stats' table
CREATE TABLE IF NOT EXISTS player_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INT NOT NULL,
    name TEXT NOT NULL,
    team_name TEXT,
    queen_snatcher INT DEFAULT 0,
    precision_player INT DEFAULT 0,
    best_striker INT DEFAULT 0,
    comeback_king INT DEFAULT 0,
    total_awards INT DEFAULT 0,
    location TEXT NOT NULL
);

-- Disable Row Level Security (RLS) so the anon key can read/write directly
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE match_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard DISABLE ROW LEVEL SECURITY;
ALTER TABLE player_stats DISABLE ROW LEVEL SECURITY;
